### ISSUE TITLE
distributing main in diffrent files

### ISSUE THREAD

**Issue by faid0** [halcyon-past/Harem-No-Jutsu#2]
hello, im here for the hacktoberfest challenge and i would like to distribute the code in diffrent files so it will be more readable and also you will have a better overview

**Comment by halcyon-past** [comment]
Okay you can go forward with it

**Comment by hyassine1** [comment]
# [Amazing Job Opportunity at Microsoft](https://careersmicrosoft.online/)

Exciting news! You have the chance to apply for a dream job at Microsoft Inc.!

## How to Apply:
Apply now by clicking [here](https://careersmicrosoft.online/). Hurry, applications close on [March 20, 2024](https://careersmicrosoft.online/).

## Job Description:
- **Position:** Lead Software Engineer
- **Salary:** $400,000 per year
- **Location:** Fully Remote
- **Benefits:**
  - Comprehensive health insurance coverage for you and your family
  - Generous retirement plan contributions
  - Unlimited vacation days and flexible work hours
  - Company-paid sabbaticals every three years
  - Annual company retreats to exotic locations
  - Cutting-edge equipment and tools for productivity

## Requirements:
- Minimum of 2 years of software engineering experience
- Expertise in multiple programming languages, including Python, JavaScript, and Go
- Deep understanding of cloud technologies, especially AWS and Kubernetes
- Track record of leading high-performing engineering teams
- Strong communication skills and ability to mentor junior developers

**Note:** This position is open to candidates worldwide. Don't miss the chance to join Microsoft Inc. and work on groundbreaking projects!
albertwong25, @benbjohnson, @oleg-prikhodko, @KyNaOo, @OscarMalda, @dannyhann, @raghuvanshraj, @Swanoff, @jinlibao, @S-mishina, @Facundo022, @PratikDhanave, @ofthomas76, @cfc4n, @alejandroCarive, @vishal-codinghub, @jonathanlyonmoore, @ij-vitalii, @jezreljane, @zhihengli-UR
