### ISSUE TITLE
Adding a DJS handler for slash commands

### ISSUE THREAD

**Issue by zapdev360** [halcyon-past/Harem-No-Jutsu#9]
The handler will include command folders separated by their respective categories, events and functions folder for handling them.
I'll also add basic slash commands for demonstration purposes, along with global error handling, so the bot doesn't crash in most cases.

In overall, you'll have an easier time migrating to DJS with this, and working on it in the future.
@halcyon-past Kindly assign me this issue, and apply the necessary labels on this issue and the upcoming PR. 👍

**Comment by halcyon-past** [comment]
@thelegendev assigned
